/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AtlasProfileRouteImport } from './routes/atlasProfile'
import { Route as AtlasHomeRouteImport } from './routes/atlasHome'
import { Route as AtlasContactRouteImport } from './routes/atlasContact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const AtlasProfileRoute = AtlasProfileRouteImport.update({
  id: '/atlasProfile',
  path: '/atlasProfile',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasHomeRoute = AtlasHomeRouteImport.update({
  id: '/atlasHome',
  path: '/atlasHome',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasContactRoute = AtlasContactRouteImport.update({
  id: '/atlasContact',
  path: '/atlasContact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlasContact': typeof AtlasContactRoute
  '/atlasHome': typeof AtlasHomeRoute
  '/atlasProfile': typeof AtlasProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlasContact': typeof AtlasContactRoute
  '/atlasHome': typeof AtlasHomeRoute
  '/atlasProfile': typeof AtlasProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlasContact': typeof AtlasContactRoute
  '/atlasHome': typeof AtlasHomeRoute
  '/atlasProfile': typeof AtlasProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/atlasContact' | '/atlasHome' | '/atlasProfile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/atlasContact' | '/atlasHome' | '/atlasProfile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atlasContact'
    | '/atlasHome'
    | '/atlasProfile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtlasContactRoute: typeof AtlasContactRoute
  AtlasHomeRoute: typeof AtlasHomeRoute
  AtlasProfileRoute: typeof AtlasProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/atlasProfile': {
      id: '/atlasProfile'
      path: '/atlasProfile'
      fullPath: '/atlasProfile'
      preLoaderRoute: typeof AtlasProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlasHome': {
      id: '/atlasHome'
      path: '/atlasHome'
      fullPath: '/atlasHome'
      preLoaderRoute: typeof AtlasHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlasContact': {
      id: '/atlasContact'
      path: '/atlasContact'
      fullPath: '/atlasContact'
      preLoaderRoute: typeof AtlasContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtlasContactRoute: AtlasContactRoute,
  AtlasHomeRoute: AtlasHomeRoute,
  AtlasProfileRoute: AtlasProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
